### ISSUE TITLE
Appinstaller steps

### ISSUE THREAD

**Issue by yowl** [dotnet/SignService#402]
I wonder if its possible to use this tool to sign and publish for AppInstaller installation?  Specifically a .net core self contained `.wapproj` published with `-r <RID>` that creates an appx and some surronding files ( `.appinstaller/index.html/ps1 etc).  `msbuild` can create the `appx` file using the publish target on the `.wapproj` project,  That creates the appx and then fails if no certificate is supplied, but I could then sign manually.  I could then grab/generate the other files from a manually build using a test certificate and publish the amalgamation of those "semi static" files, along with the SignService signed appx.  Is that a stupid idea or my best bet?

**Comment by clairernovotny** [comment]
We do this with NuGet Package Explorer, but not directly in the publish target. 

Check out the repo and how we do things there: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

For example: package signing is disabled since the service will do it:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/PackageExplorer.Package/PackageExplorer.Package.wapproj#L43

Also, we have different package id's for different release channels so the Store, CI, and local dev can all run SxS.
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/PackageExplorer.Package/PackageExplorer.Package.wapproj#L60-L69

We auto version the app manifest in CI prior to the build step:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/azure-pipelines.yml#L96-L99

We also pass all the relevant files to the sign client (as it puts the right cert info in the appinstaller):
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/azure-pipelines.yml#L264-L275

**Comment by yowl** [comment]
Thanks, I think there is a small issue with https://github.com/dotnet/SignService/blob/e485561013bc7f96d3e136b6d77e76a0db891f3a/src/SignService/SigningTools/AppInstallerService.cs#L48

It looks for a tag `MainBundle` but I have `MainPackage ` :
```
<AppInstaller Uri="http://....." Version="1.0.1.39" xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2">
	<MainPackage Name="D0B5B5BE-F6E9-48F9-B94E-16ED695EFDFF" Version="1.0.1.39" Publisher="CN=...
```

**Comment by clairernovotny** [comment]
Fair -- care to submit a PR with a fix? :)

**Comment by yowl** [comment]
Will do.  Thanks for the help.  As often I made a mountain out of a mole hill and this was actually quite simple 😊

**Comment by yowl** [comment]
One other thing if someone gets here.  Not related to SignService, but if you encounter invalid XML failures, check you are not hitting https://github.com/MicrosoftDocs/msix-docs/issues/191
